[package]
name = "morphing"
version = "0.1.0"
edition = "2021"

[dependencies]
comemo = "0.4.0"
itertools = "0.13.0"
parking_lot = "0.12.3"
typst = "0.12.0"
typst-kit = { version = "0.12.0", features = ["embed-fonts"] }
typst-svg = "0.12.0"
